# Generated by Django 4.1.6 on 2023-04-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
    ]
