# Generated by Django 4.1.6 on 2023-04-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='XS', max_length=3, verbose_name='Размер'),
        ),
    ]
