# Generated by Django 4.1.6 on 2023-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_create',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
