# Generated by Django 4.1.6 on 2023-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
