# Generated by Django 4.1.6 on 2023-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.TextField(max_length=200, null=True, verbose_name='Номер телефона'),
        ),
    ]
