# Generated by Django 4.1.6 on 2023-06-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_order_comment_order_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
    ]
